version: '3'
services:
  ############################
  # read-file + Dapr sidecar
  ############################
  read-file:
    build:
      context: ./fsharp
      dockerfile: ReadFile/Dockerfile         
    ports:
      - "3001:3000"
    environment: 
      - PORT=3000
    depends_on:
      - redis
      - placement
    networks:
      - vow-dapr
  read-file-dapr:
    image: "daprio/daprd:1.2.0"
    command: ["./daprd",
     "-app-id", "read-file",
     "-app-port", "3000",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    depends_on:
      - read-file
    network_mode: "service:read-file"

  ############################
  # events-store + Dapr sidecar
  ############################
  events-store:
    build:
      context: ./fsharp
      dockerfile: EventsStore/Dockerfile         
    ports:
      - "3002:3000"
    environment: 
      - PORT=3000
    depends_on:
      - redis
      - placement
    networks:
      - vow-dapr
  events-store-dapr:
    image: "daprio/daprd:1.2.0"
    command: ["./daprd",
     "-app-id", "events-store",
     "-app-port", "3000",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    depends_on:
      - events-store
    network_mode: "service:events-store"
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - vow-dapr
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - vow-dapr
networks:
    vow-dapr: