version: '3'
services:
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  zipkin:
    image: openzipkin/zipkin-slim
    ports:
    - "5411:9411"
  
  ############################
  # read-file + Dapr sidecar
  ############################
  read-file:
    build:
      context: ./fsharp
      dockerfile: ReadFile/Dockerfile         
    ports:
      - "3001:3000"
    environment: 
      - PORT=3000
      - SeqHost=http://seq
      - ElasticHost=
    depends_on:
      - redis
      - placement
  read-file-dapr:
    image: "daprio/daprd:1.2.0"
    command: ["./daprd",
     "-app-id", "read-file",
     "-app-port", "3000",
     "-placement-host-address", "placement:50006",
     "-components-path", "/dapr/components",
     "-config", "/dapr/config.yaml"]
    volumes:
        - "./dapr/:/dapr"
    depends_on:
      - read-file
    network_mode: "service:read-file"

  ############################
  # update-store + Dapr sidecar
  ############################
  update-store:
    build:
      context: ./fsharp
      dockerfile: UpdateStore/Dockerfile         
    ports:
      - "3002:3000"
    environment: 
      - PORT=3000
      - SeqHost=http://seq
      - ElasticHost=
    depends_on:
      - redis
      - placement
  update-store-dapr:
    image: "daprio/daprd:1.2.0"
    command: ["./daprd",
     "-app-id", "update-store",
     "-app-port", "3000",
     "-placement-host-address", "placement:50006",
     "-components-path", "/dapr/components",
     "-config", "/dapr/config.yaml"]
    volumes:
        - "./dapr/:/dapr"
    depends_on:
      - update-store
    network_mode: "service:update-store"
  ############################
  # store-doc + Dapr sidecar
  ############################
  store-doc:
    build:
      context: ./fsharp
      dockerfile: StoreDoc/Dockerfile         
    ports:
      - "3003:3000"
    environment: 
      - PORT=3000
      - SeqHost=http://seq
      - ElasticHost=
    depends_on:
      - redis
      - placement
  store-doc-dapr:
    image: "daprio/daprd:1.2.0"
    command: ["./daprd",
      "-app-id", "store-doc",
      "-app-port", "3000",
      "-placement-host-address", "placement:50006",
      "-components-path", "/dapr/components",
      "-config", "/dapr/config.yaml"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - store-doc
    network_mode: "service:store-doc"
  ############################
  # ya-ocr + Dapr sidecar
  ############################
  ya-ocr:
    build:
      context: ./fsharp
      dockerfile: YaOCR/Dockerfile         
    ports:
      - "3004:3000"
    environment: 
      - PORT=3000
      - SeqHost=http://seq
      - ElasticHost=
    depends_on:
      - redis
      - placement
  ya-ocr-dapr:
    image: "daprio/daprd:1.2.0"
    command: ["./daprd",
      "-app-id", "ya-ocr",
      "-app-port", "3000",
      "-placement-host-address", "placement:50006",
      "-components-path", "/dapr/components",
      "-config", "/dapr/config.yaml"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - ya-ocr
    network_mode: "service:ya-ocr"

  ############################
  # label-doc + Dapr sidecar
  ############################
  label-doc:
    build:
      context: ./py
      dockerfile: label-doc.Dockerfile         
    ports:
      - "3005:3000"
    environment: 
      - PORT=3000
      - SeqHost=http://seq
      - ElasticHost=
    depends_on:
      - redis
      - placement
  label-doc-dapr:
    image: "daprio/daprd:1.2.0"
    command: ["./daprd",
      "-app-id", "label-doc",
      "-app-port", "3000",
      "-placement-host-address", "placement:50006",
      "-components-path", "/dapr/components",
      "-app-protocol", "grpc",
      "-config", "/dapr/config.yaml"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - label-doc
    network_mode: "service:label-doc"
    
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
