
@BASE_URL=http://localhost
@READ_FILE_URL=http://192.168.0.103:3010
@QUERY_PARSED_URL=http://192.168.0.103:3050
#@READ_FILE_URL=https://vow.perimeter.pw
#@QUERY_PARSED_URL=https://vow.perimeter.pw

GET {{BASE_URL}}:3010/dapr/subscribe

##########

## ReadDocEvent consumed by ya-ocr
POST {{BASE_URL}}:3010/$pubsub/doc-read

Content-Type: application/json

{ "id": "111",
  "specVersion": "1",
  "source": "test",
  "type": "test",
  "dataContentType": "test",    
  "data": {
    "docKey": "xxx",
    "docContent": "yyy"
  }
}
###########
POST {{READ_FILE_URL}}/upload/base64
Content-Type: application/json

{
    "docKey": "333",
    "base64": "xxx"
}

#############
# POST {{BASE_URL}}:3010/upload/file
## upload
# POST http://b6fad0f1f512.ngrok.io/upload
//POST https://d5dpfrp927m5qv1v5bg8.apigw.yandexcloud.net/upload
// POST https://functions.yandexcloud.net/d4e5te3r3hsmg4rcr6lj
//POST http://b6fad0f1f512.ngrok.io/upload/file
POST {{READ_FILE_URL}}/upload/file
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="docKey";

888
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="passport-3.jpg"
Content-Type: image/jpg

< ./images/passport-3.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

#############

## query-parsed 
##GET {{BASE_URL}}:3050/docs/777/parsed
# GET http://192.168.0.105/docs/123/parsed
#GET https://d5dpfrp927m5qv1v5bg8.apigw.yandexcloud.net/docs/888/parsed
#GET https://d5dpfrp927m5qv1v5bg8.apigw.yandexcloud.net/docs/444/parsed
GET {{QUERY_PARSED_URL}}/docs/888/parsed

#############

GET http://localhost:3500/v1.0/secrets/vow-docs/vow-docs-ya