@BASE_URL=http://localhost:3001


## upload

POST {{BASE_URL}}/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

file
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="passport-1.jpg"
Content-Type: image/jpg

< ./images/passport-1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


///
{"docKey": "111", "docContent": "111a222"}
