POST https://iam.api.cloud.yandex.net/iam/v1/tokens HTTP/1.1
content-type: application/json

{ "jwt":
   "eyJraWQiOiJsZmtvZTM1aHNrNThha3MzMDFubCIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJhdWQiOiJodHRwczovL2lhbS5hcGkuY2xvdWQueWFuZGV4Lm5ldC9pYW0vdjEvdG9rZW5zIiwiZXhwIjoxNjIyODkxODM5LCJpYXQiOjE2MjI4ODgyMzksImlzcyI6ImFqZXBnMG1qdDA2c2l1YTY1dXNtIn0.CdPro3xvPSwJdsgcayYjps97ww8WLX2uqUfY0_pcQF8DvPsvrh9ZKtd5FVmJCnR-xBUlZAwO03zDjCic2hNWeT7LFsJanbsmvHO-NMaM6JYazUKfWs2S58nm5YL17eAgeEdIuFg2S0jx4QFfXkbB5xvIhvvQw38vx5kjGCdMAEY27wn2puYdyQLubrxOi7XxkkZpI1pFIbMyI8bn96XUUqYt4f4YI4M2_MwxJFWlBaLQt2IRz_3I8LFsbAXoUx84Pyfwz_CC6JlITbcjRTVyQUWLwZ-nn4ukEMB0O8xLmNy0mFj-TpGF5XEq_otKO8aBl4QaK6we0WPk3M039RETwg" }