POST https://iam.api.cloud.yandex.net/iam/v1/tokens HTTP/1.1
content-type: application/json

{ "jwt":
   "eyJhbGciOiJQUzI1NiIsImtpZCI6ImFqZWNqMXByNWk2MDc1Y2VpdGt0IiwidHlwZSI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2lhbS5hcGkuY2xvdWQueWFuZGV4Lm5ldC9pYW0vdjEvdG9rZW5zIiwiZXhwIjoxNjIyODkzOTAwLCJpYXQiOjE2MjI4OTAzMDAsImlzcyI6ImFqZTN0anVnYTRmaHZ0czA1YnR2In0.Eyn1P8uSOnDkY1RGTr_YF4mnnv2wI3I88mxIAgLTAG9GV_e7vwDKRWkogey4tibHZaz7sLP8Act_HlMXq_NajbzrqqGGE4zfMZ6wdpFEvggB3JcwtypS9G7ATrrZSwJKBLTEf9BGca7pUBbng7Mip-3970CsGcAnJQlZy6Wz3wIsDQzgLozJLAShG8efQFxFXtmQERlB001FUHNSY73Hu4_bAVczmsQ44ZhKk-NDml-UApM9eBtYtpY2Qnhb66FUPb_GeCRd_4O8thcOxu3AML-D-ZESazRr7VVgfPPkTOgLOJznqcGMysK4IhHZZxJu1QmjbG9GnauTfW41vgVvxw" }