apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-secrets-store
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: "C:/dev/vow-docs/dapr/dapr/secrets/my-secrets.json"
  - name: nestedSeparator
    value: ":"
